//! The wire shape, recorded per protocol version (GH #18).
//!
//! Every other wire test in this tree answers *"is the shape right?"*.
//! None of them answers *"did the shape move without the version
//! moving?"*, which is the question §23.3 turns into a compatibility
//! promise and the question nothing in the tree could fail on. Six
//! pre-tag commits changed the wire and left [`PROTOCOL_MINOR`] alone;
//! that was defensible then and is not now (GH #16 ratified the `v0.0.5`
//! tag as the boundary), and the diff of the seventh looks exactly like
//! the diff of the first.
//!
//! # What this records
//!
//! A text document — [`shape_document`] — built from the **encoded
//! bytes** of the live types, and compared against
//! `tests/wire-shape/<major>.<minor>.golden`. It is keyed to the
//! serialised surface, not to the source text, which is the property
//! that decides whether a guard survives contact with real work: a
//! comment, a private helper, a renamed local, a reordered struct field
//! and a reordered `use` all leave this document byte-identical, so
//! nobody learns to bump the constant reflexively to make a red go away.
//!
//! Three dimensions per type, because no one of them sees everything:
//!
//! * **`wire:`** — the CBOR the encoder actually emits, keys sorted.
//!   Sees added, removed, renamed and retyped fields, and the `type` tag
//!   of every frame variant. Blind to a field that `skip_serializing_if`
//!   dropped, which is why the next line exists.
//! * **`declared:`** — the field names from the derived [`Debug`], which
//!   prints a field whether or not the encoder skipped it. This is what
//!   catches a new `Option` field recorded with a `None` sample: the
//!   `wire:` line would not move, and this one does.
//! * **`variants:`** — serde's own list, read out of the error it raises
//!   for an unknown discriminator (see [`serde_variants`]). Generated by
//!   the `derive`, so unlike a hand-kept catalogue it cannot be
//!   forgotten. `frames.rs`'s `KNOWN_SERVER_TYPES` is hand-kept and has
//!   the matching hole — a variant added with a `tag()` arm but no
//!   catalogue entry leaves that file's assertions green — and this line
//!   closes it for free. It is also post-`rename`, where `tag()` is a
//!   Rust method and cannot see a `#[serde(rename)]` at all.
//!
//! # How it forces the version decision
//!
//! The golden is named for the version it describes and
//! [`RECORDED_VERSIONS`] lists the ones that exist. After a wire change
//! there are exactly two green paths, and both of them move the
//! constant:
//!
//! 1. bump [`PROTOCOL_MINOR`] (additive) or [`PROTOCOL_MAJOR`]
//!    (breaking) in `protocol/handshake.rs`;
//! 2. add the new pair to [`RECORDED_VERSIONS`];
//! 3. write the new document to the golden named for it.
//!
//! The third path — editing `1.0.golden` in place — is the one this
//! guard exists to make visible. It is not prevented, because a checked-in
//! file cannot be; it is made to *read* as what it is, a claim that this
//! shape was always protocol 1.0, in a diff a reviewer sees. That is why
//! there is deliberately **no `--bless` flag and no `HOLDFAST_RECORD_…`
//! env var**: a one-command "regenerate the snapshot" affordance is
//! indistinguishable from routine hygiene, and it would train exactly the
//! reflex the issue is about. Re-recording is a copy-paste out of the
//! failure message, which is proportionate for something that happens
//! once per protocol version.
//!
//! # Scope, and the one blind spot
//!
//! Covered: the framing constants, the `control.sock` envelope and its
//! error payload, the handshake, the three `daemon/*` method payloads,
//! and the whole `attach.sock` frame catalogue.
//!
//! **Not covered, and nothing here would notice:** a *new* `daemon/*`
//! method payload struct. `Request.params` and `Response.data` are opaque
//! `CborValue`, so there is no registry of payload types to enumerate the
//! way [`serde_variants`] enumerates a frame catalogue — the list in
//! [`control_payloads`] is hand-kept and has a hand-kept list's hole. The
//! `[tokens]` section narrows it (a new method needs a `METHOD_*` const,
//! and that scan *is* exhaustive over `protocol/`), so the *method* is
//! caught even when its payload type is not. Recorded here rather than
//! papered over: a guard whose limits are written down is worth more than
//! one that implies it has none.
//!
//! Also out of scope, deliberately: `tool/<name>` params and results, and
//! the `resource/*` payloads. Those are MCP's surface, advertised to the
//! client at runtime by `tools/list` and owned by `tests/schema.rs`; they
//! are forwarded through this wire rather than defined by it.

use std::collections::BTreeSet;
use std::fmt::Debug;
use std::path::PathBuf;

use serde::de::DeserializeOwned;
use serde::Serialize;

use holdfast_core::attach::frames::{
    ApprovalDecision, AttachMode, AttachRole, ClientFrame, ServerFrame, SignalName,
};
use holdfast_core::daemon::server::{DaemonStatus, StopOutcome, StopParams};
use holdfast_core::protocol::frame::{self, LENGTH_PREFIX_BYTES, MAX_FRAME_BYTES};
use holdfast_core::protocol::handshake::{ClientKind, HandshakeData, HandshakeParams};
use holdfast_core::protocol::handshake::{PROTOCOL_MAJOR, PROTOCOL_MINOR};
use holdfast_core::protocol::method::{CborValue, ControlError, ErrorCode, Request, Response};

/// Every protocol version whose shape is recorded under `tests/wire-shape/`.
///
/// **Append-only.** A row is the statement *"protocol M.m looked like
/// this"*, and a peer built against that version is entitled to it. The
/// current build must be the last row — you cannot be speaking a protocol
/// older than one already recorded.
const RECORDED_VERSIONS: &[(u32, u32)] = &[
    // 1.0 — 0.0.5's control protocol plus 0.0.6's attach frames. The
    // first shape recorded at all; everything before it is pre-tag and
    // has no record, which is the gap GH #18 is about.
    (1, 0),
];

/// The placeholder every opaque string field carries in this file.
///
/// [`shape`] renders text **literally**, because for an enum-valued field
/// the spelling *is* the wire contract — `"ui-bridge"` and `"UiBridge"`
/// are different protocols. That only works if free-form strings are not
/// also rendered literally, or the document would move whenever a sample
/// value did. So every `String` whose content the wire does not fix
/// carries this, and the golden shows `"<str>"` exactly where a peer is
/// free to send anything.
const STR: &str = "<str>";

// ---------------------------------------------------------------------
// Rendering the encoded form
// ---------------------------------------------------------------------

/// The CBOR a value actually encodes to, read back from the framed bytes.
///
/// Through [`frame::encode`] rather than `CborValue::serialized` on
/// purpose: these are the bytes that go on the socket, and the existing
/// key-set tests in `frames.rs` and `method.rs` read them the same way.
fn wire_form<T: Serialize>(value: &T) -> CborValue {
    let framed = frame::encode(value).expect("a wire sample must encode");
    frame::decode(&framed[LENGTH_PREFIX_BYTES..]).expect("a frame body is CBOR")
}

/// A value's shape: keys and kinds, with text kept verbatim.
///
/// Map keys are **sorted**, following §7.4's own position that the wire
/// fixes the field names and not a map order — the same reason
/// `frame_bodies_are_cbor_maps_keyed_by_the_7_4_1_field_names` compares a
/// set. Reordering a struct's fields is therefore not a wire change and
/// does not move this document.
fn shape(value: &CborValue) -> String {
    match value {
        CborValue::Null => "null".to_string(),
        CborValue::Bool(_) => "bool".to_string(),
        CborValue::Integer(_) => "int".to_string(),
        CborValue::Float(_) => "float".to_string(),
        CborValue::Bytes(_) => "bytes".to_string(),
        CborValue::Text(t) => format!("{t:?}"),
        CborValue::Array(items) => {
            let inner: Vec<String> = items.iter().map(shape).collect();
            format!("[{}]", inner.join(", "))
        }
        CborValue::Map(entries) => {
            let mut fields: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    let key = k.as_text().expect(
                        "a wire map is keyed by text; an integer-keyed map is a different \
                         wire format and this guard would render it as one type",
                    );
                    format!("{key}: {}", shape(v))
                })
                .collect();
            fields.sort();
            format!("{{{}}}", fields.join(", "))
        }
        other => format!("UNRENDERED({other:?})"),
    }
}

/// The field names the derived [`Debug`] prints, which is every declared
/// field — including one `skip_serializing_if` kept off the wire.
///
/// Reads names only, never values: a value would put sample data in the
/// golden and make the document move whenever a fixture did.
///
/// **Sorted**, for the same reason [`shape`] sorts map keys. `Debug`
/// prints in declaration order, so an unsorted list would report a pure
/// field *reorder* as a wire change — and reordering a struct's fields
/// does not move a CBOR map, which is why §7.4's own key-set test
/// compares a set. This line answers *which fields exist*; `wire:`
/// answers what the encoder does with them.
fn declared_fields<T: Debug>(value: &T) -> Vec<String> {
    let mut names = debug_field_names(&format!("{value:?}"));
    names.sort();
    names
}

/// [`declared_fields`]'s parser, split out so it can be tested against
/// strings whose answer is known.
///
/// Depth-1 identifiers followed by `:`. Nested braces, brackets and
/// parentheses are skipped so a `Some(..)` or an inner struct does not
/// contribute its own fields, and string literals are skipped so a `:`
/// inside sample text is not read as a field boundary.
fn debug_field_names(rendered: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut depth: usize = 0;
    let mut in_string = false;
    let mut escaped = false;
    let mut ident = String::new();

    for ch in rendered.chars() {
        if in_string {
            if escaped {
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == '"' {
                in_string = false;
            }
            continue;
        }
        match ch {
            '"' => {
                in_string = true;
                ident.clear();
            }
            '{' | '[' | '(' => {
                depth += 1;
                ident.clear();
            }
            '}' | ']' | ')' => {
                depth = depth.saturating_sub(1);
                ident.clear();
            }
            ':' if depth == 1 && !ident.is_empty() => {
                names.push(std::mem::take(&mut ident));
            }
            c if c.is_alphanumeric() || c == '_' => ident.push(c),
            _ => ident.clear(),
        }
    }
    names
}

/// serde's own variant list for `T`, taken from the error it raises for a
/// discriminator it does not know.
///
/// This is the only enumeration in this file that cannot go stale,
/// because the `derive` generates it: a new variant is in this list the
/// moment it compiles, with no catalogue to remember to update. It is
/// also the *serialised* spelling — post-`rename`/`rename_all`, and
/// excluding `#[serde(skip)]` variants such as `ServerFrame::Unknown`,
/// which is correct since a skipped variant is not on the wire.
///
/// The extraction panics rather than returning empty if serde stops
/// phrasing the error this way. A version of this that silently answered
/// `vec![]` would record an empty variant list in the golden, match it
/// forever, and be the exact failure mode — a guard that passes because
/// it cannot see — this file is written against.
fn serde_variants<T: DeserializeOwned>(probe: CborValue) -> Vec<String> {
    let err = probe
        .deserialized::<T>()
        .err()
        .expect("the probe discriminator must not be a real variant");
    variants_in(&err.to_string())
}

/// [`serde_variants`]'s parser, split out so it can be tested against
/// messages whose answer is known.
///
/// serde phrases the list three different ways depending on how many
/// variants there are — `` expected `a` ``, `` expected `a` or `b` ``,
/// and `` expected one of `a`, `b`, `c` `` — which this guard discovered
/// the hard way on its first run, when `AttachMode` and `AttachRole`
/// (two variants each) took the middle form. So the extraction reads the
/// **backtick-delimited spans** after `expected` rather than splitting on
/// any one separator: that is the part of the phrasing all three share,
/// and it survives a fourth.
fn variants_in(message: &str) -> Vec<String> {
    assert!(
        message.contains("unknown variant"),
        "the probe discriminator did not produce serde's unknown-variant error, so this is \
         not a variant list: {message}"
    );
    let (_, tail) = message.split_once("expected ").unwrap_or_else(|| {
        panic!(
            "serde no longer reports its variant list in the form this guard reads, so the \
             guard is blind to a new frame variant. Re-derive the extraction from: {message}"
        )
    });
    let found: Vec<String> = tail
        .split('`')
        .skip(1)
        .step_by(2)
        .map(str::to_string)
        .collect();
    assert!(
        !found.is_empty(),
        "no variant names were extracted, which would record an empty catalogue and match \
         it forever. From: {message}"
    );
    found
}

/// The probe an internally-tagged frame enum rejects: a `type` no build
/// declares.
fn tagged_probe() -> CborValue {
    CborValue::Map(vec![(
        CborValue::Text("type".into()),
        CborValue::Text("HoldfastWireShapeProbeNotAVariant".into()),
    )])
}

/// The probe a string-serialised enum rejects.
fn plain_probe() -> CborValue {
    CborValue::Text("HoldfastWireShapeProbeNotAVariant".into())
}

/// The `type` tag a frame sample encodes to.
fn tag_of(value: &CborValue) -> String {
    let CborValue::Map(entries) = value else {
        panic!("§7.5's frames are CBOR maps, got {value:?}")
    };
    entries
        .iter()
        .find(|(k, _)| k.as_text() == Some("type"))
        .and_then(|(_, v)| v.as_text())
        .expect("§7.5 tags every frame with a `type`")
        .to_string()
}

// ---------------------------------------------------------------------
// The samples
// ---------------------------------------------------------------------

/// Every sample is **maximal**: each `Option` is `Some`, so
/// `skip_serializing_if` hides nothing from the `wire:` line. The
/// `declared:` line is what keeps that honest — set one of these to
/// `None` and the two lines disagree in the golden.
fn control_payloads() -> Vec<(&'static str, String, Vec<String>)> {
    let mut out = Vec::new();

    let request = Request {
        id: 1,
        method: STR.into(),
        params: CborValue::Map(vec![]),
    };
    out.push(entry("Request", &request));

    let response = Response {
        id: 1,
        status: STR.into(),
        data: CborValue::Map(vec![]),
        details: STR.into(),
    };
    out.push(entry("Response", &response));

    let control_error = ControlError {
        code: STR.into(),
        message: STR.into(),
        retriable: true,
        rpc_code: Some(-32602),
    };
    out.push(entry("ControlError", &control_error));

    let handshake_params = HandshakeParams {
        protocol_major: 1,
        protocol_minor: 0,
        client_kind: ClientKind::Shim,
        client_version: STR.into(),
    };
    out.push(entry("HandshakeParams", &handshake_params));

    let handshake_data = HandshakeData {
        protocol_major: 1,
        protocol_minor: 0,
        daemon_version: STR.into(),
        build: STR.into(),
        accepted: true,
        reject_reason: Some(STR.into()),
    };
    out.push(entry("HandshakeData", &handshake_data));

    let daemon_status = DaemonStatus {
        pid: 1,
        uptime_secs: 1,
        version: STR.into(),
        sessions_live: 1,
        sessions_exited_retained: 1,
        attach_clients: 1,
        bridge_sessions: 1,
    };
    out.push(entry("DaemonStatus", &daemon_status));

    let stop_params = StopParams {
        force: Some(true),
        timeout_secs: Some(1),
    };
    out.push(entry("StopParams", &stop_params));

    let stop_outcome = StopOutcome {
        stopped_at_unix_secs: 1,
        sessions_terminated: 1,
    };
    out.push(entry("StopOutcome", &stop_outcome));

    out
}

/// One sample per `ClientFrame` variant, maximal.
///
/// A new variant does not have to be added here for the guard to fire:
/// [`the_sample_set_covers_every_variant_serde_knows_about`] compares
/// this list against serde's, so the omission is itself the failure.
fn client_frames() -> Vec<ClientFrame> {
    vec![
        ClientFrame::Attach {
            session: STR.into(),
            mode: AttachMode::ReadWrite,
            role: AttachRole::Interactive,
            client_kind: ClientKind::Shim,
            client_version: STR.into(),
            protocol_major: 1,
            protocol_minor: 0,
        },
        ClientFrame::Input { bytes: vec![0x1b] },
        ClientFrame::SecretInput {
            request_id: STR.into(),
            bytes: vec![0x1b],
        },
        ClientFrame::Resize { cols: 1, rows: 1 },
        ClientFrame::Signal {
            sig: SignalName::Int,
        },
        ClientFrame::ApproveBinding {
            approval_id: STR.into(),
            decision: ApprovalDecision::Approve,
        },
        ClientFrame::Detach,
    ]
}

/// One sample per `ServerFrame` variant, maximal.
///
/// `Unknown` is absent because it is `#[serde(skip)]` and cannot be
/// encoded — and serde leaves it out of its own variant list for the same
/// reason, so the cross-check agrees. Removing the `skip` puts it in
/// serde's list, and the cross-check then fails for want of a sample.
fn server_frames() -> Vec<ServerFrame> {
    vec![
        ServerFrame::Attached {
            session_id: STR.into(),
            name: Some(STR.into()),
            cols: 1,
            rows: 1,
            state: STR.into(),
            exit_code: Some(0),
            protocol_major: 1,
            protocol_minor: 0,
        },
        ServerFrame::AttachReject {
            reason: STR.into(),
            message: STR.into(),
        },
        ServerFrame::Output {
            session: STR.into(),
            bytes: vec![0x1b],
        },
        ServerFrame::SessionExited { code: 0 },
        ServerFrame::Resize { cols: 1, rows: 1 },
        ServerFrame::AwaitingSecret {
            request_id: STR.into(),
            prompt_text: STR.into(),
        },
        ServerFrame::SecretRequestClosed {
            request_id: STR.into(),
            outcome: STR.into(),
        },
        ServerFrame::BindingApprovalRequired {
            approval_id: STR.into(),
            binding_name: STR.into(),
            provider: STR.into(),
            session: STR.into(),
            prompt_text: STR.into(),
        },
        ServerFrame::ProtocolError {
            reason: STR.into(),
            frame_kind: Some(STR.into()),
        },
        ServerFrame::Detached { reason: STR.into() },
    ]
}

/// `(label, wire shape, declared fields)` for one sample.
fn entry<T: Serialize + Debug>(
    label: &'static str,
    value: &T,
) -> (&'static str, String, Vec<String>) {
    (label, shape(&wire_form(value)), declared_fields(value))
}

/// The `declared:` line's body.
///
/// A unit variant such as `ClientFrame::Detach` has no fields, and the
/// record has to say so in a word rather than with an empty line — a
/// blank there is indistinguishable from a scanner that returned
/// nothing, and it would put trailing whitespace in a checked-in file.
fn declared_line(fields: &[String]) -> String {
    if fields.is_empty() {
        "(none)".to_string()
    } else {
        fields.join(", ")
    }
}

// ---------------------------------------------------------------------
// The wire tokens that live in `protocol/` as constants
// ---------------------------------------------------------------------

/// Every `pub const NAME: &str = "…"` under `src/protocol/`.
///
/// These are the wire's *vocabulary* — the method names of §7.4.1, the
/// `tool/` prefix, §18.3a's two reject tokens — and a new method is the
/// textbook additive change [`PROTOCOL_MINOR`]'s own doc names. There is
/// no runtime enumeration of them (they are free-standing consts, not an
/// array), so this one dimension is read from the source. That is the
/// weaker instrument and it is used only where nothing stronger exists;
/// it matches a **declaration**, so prose that mentions a method name
/// does not enter the document and a comment cannot move it.
fn wire_tokens() -> Vec<String> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/protocol");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "rs"))
        .collect();
    files.sort();
    assert!(
        files.len() >= 4,
        "the scan found only {} files under {} — a walk that reaches nothing reports no \
         tokens and matches an empty record forever",
        files.len(),
        dir.display()
    );

    let mut tokens = Vec::new();
    for file in &files {
        let text = std::fs::read_to_string(file).expect("read a protocol source file");
        for line in text.lines() {
            if let Some(token) = str_const_declaration(line) {
                tokens.push(token);
            }
        }
    }
    tokens.sort();
    tokens
}

/// `NAME = "value"` if this line *declares* a public `&str` const.
fn str_const_declaration(line: &str) -> Option<String> {
    let code = line.trim_start();
    if code.starts_with("//") {
        return None;
    }
    let rest = code.strip_prefix("pub const ")?;
    let (name, rest) = rest.split_once(':')?;
    let rest = rest.trim_start().strip_prefix("&str")?;
    let rest = rest.trim_start().strip_prefix('=')?;
    let rest = rest.trim_start().strip_prefix('"')?;
    let value = rest.split_once('"')?.0;
    Some(format!("{} = {:?}", name.trim(), value))
}

// ---------------------------------------------------------------------
// The document
// ---------------------------------------------------------------------

fn shape_document() -> String {
    let mut doc = String::new();
    doc.push_str(&format!(
        "# holdfast wire shape — protocol {PROTOCOL_MAJOR}.{PROTOCOL_MINOR}\n"
    ));
    doc.push_str(
        "#\n\
         # Generated from the encoded bytes of the live types by\n\
         # crates/holdfast-core/tests/wire_shape.rs. Read that file before\n\
         # editing this one: a version already recorded here is a promise to\n\
         # every peer built against it, and rewriting a row in place is the\n\
         # thing the guard exists to make visible (GH #18).\n\
         #\n\
         #   declared: the fields the type has, including any the encoder skips\n\
         #   wire:     the CBOR actually emitted, keys sorted\n\
         #   variants: serde's own list, generated by the derive\n\
         \n",
    );

    doc.push_str("[framing]\n");
    doc.push_str(&format!("LENGTH_PREFIX_BYTES = {LENGTH_PREFIX_BYTES}\n"));
    doc.push_str(&format!("MAX_FRAME_BYTES = {MAX_FRAME_BYTES}\n"));
    doc.push('\n');

    doc.push_str("[tokens]\n");
    for token in wire_tokens() {
        doc.push_str(&format!("{token}\n"));
    }
    doc.push('\n');

    // §18.3's rows are ORDER-BOUND — §18's preamble makes the catalogue's
    // order normative, and `error_codes_are_the_spec_18_3_table_in_catalog_order`
    // is the test that owns it against the spec. This is a sequence, not a
    // set, for that reason: sorting here would record a document that a
    // reordered catalogue still matched.
    doc.push_str("[error-codes] (ordered — §18.3 row order)\n");
    for code in ErrorCode::ALL {
        doc.push_str(&format!("{}\n", code.as_str()));
    }
    doc.push('\n');

    doc.push_str("[vocabularies]\n");
    for (label, variants) in vocabularies() {
        doc.push_str(&format!("{label}: {}\n", variants.join(", ")));
    }
    doc.push('\n');

    doc.push_str("[control]\n");
    for (label, wire, declared) in control_payloads() {
        doc.push_str(&format!("{label}\n"));
        doc.push_str(&format!("  declared: {}\n", declared_line(&declared)));
        doc.push_str(&format!("  wire:     {wire}\n"));
    }
    doc.push('\n');

    doc.push_str("[attach.client]\n");
    doc.push_str(&format!(
        "variants: {}\n",
        serde_variants::<ClientFrame>(tagged_probe()).join(", ")
    ));
    for f in client_frames() {
        let wire = wire_form(&f);
        doc.push_str(&format!("ClientFrame::{}\n", tag_of(&wire)));
        doc.push_str(&format!(
            "  declared: {}\n",
            declared_line(&declared_fields(&f))
        ));
        doc.push_str(&format!("  wire:     {}\n", shape(&wire)));
    }
    doc.push('\n');

    doc.push_str("[attach.server]\n");
    doc.push_str(&format!(
        "variants: {}\n",
        serde_variants::<ServerFrame>(tagged_probe()).join(", ")
    ));
    for f in server_frames() {
        let wire = wire_form(&f);
        doc.push_str(&format!("ServerFrame::{}\n", tag_of(&wire)));
        doc.push_str(&format!(
            "  declared: {}\n",
            declared_line(&declared_fields(&f))
        ));
        doc.push_str(&format!("  wire:     {}\n", shape(&wire)));
    }

    doc
}

/// The enums that reach the wire as bare strings, with serde's list of
/// their spellings.
fn vocabularies() -> Vec<(&'static str, Vec<String>)> {
    vec![
        ("ClientKind", serde_variants::<ClientKind>(plain_probe())),
        ("AttachMode", serde_variants::<AttachMode>(plain_probe())),
        ("AttachRole", serde_variants::<AttachRole>(plain_probe())),
        ("SignalName", serde_variants::<SignalName>(plain_probe())),
        // §7.5's `ApproveBinding.decision`, a closed set of two. Listed
        // here for the same reason `SignalName` is: the `wire:` line
        // below records one *sample*, so only one of the two spellings
        // would otherwise be in the document, and `deny` is exactly the
        // value a `rename_all` change would move unnoticed.
        (
            "ApprovalDecision",
            serde_variants::<ApprovalDecision>(plain_probe()),
        ),
    ]
}

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/wire-shape")
}

fn golden_path(major: u32, minor: u32) -> PathBuf {
    golden_dir().join(format!("{major}.{minor}.golden"))
}

/// The differing lines, as a reviewable list.
///
/// A longest-common-subsequence diff rather than a positional one. The
/// first draft compared line `i` to line `i` and, measured against a
/// single added method constant, reported **nine** changed lines: every
/// entry after the insertion point had shifted by one. A red that prints
/// nine lines when one thing moved is a red people learn to skim, and
/// this guard's whole value is that its failures get read.
fn diff(recorded: &str, current: &str) -> String {
    let a: Vec<&str> = recorded.lines().collect();
    let b: Vec<&str> = current.lines().collect();

    let mut lcs = vec![vec![0usize; b.len() + 1]; a.len() + 1];
    for i in (0..a.len()).rev() {
        for j in (0..b.len()).rev() {
            lcs[i][j] = if a[i] == b[j] {
                lcs[i + 1][j + 1] + 1
            } else {
                lcs[i + 1][j].max(lcs[i][j + 1])
            };
        }
    }

    let mut out = Vec::new();
    let (mut i, mut j) = (0, 0);
    while i < a.len() && j < b.len() {
        if a[i] == b[j] {
            i += 1;
            j += 1;
        } else if lcs[i + 1][j] >= lcs[i][j + 1] {
            out.push(format!("  -{}", a[i]));
            i += 1;
        } else {
            out.push(format!("  +{}", b[j]));
            j += 1;
        }
    }
    out.extend(a[i..].iter().map(|l| format!("  -{l}")));
    out.extend(b[j..].iter().map(|l| format!("  +{l}")));
    out.join("\n")
}

// ---------------------------------------------------------------------
// The guard
// ---------------------------------------------------------------------

#[test]
fn the_wire_shape_matches_the_record_for_this_protocol_version() {
    let current = shape_document();
    // A record whose diffs are noisy is a record nobody reads, and
    // trailing whitespace is the cheapest way to get there.
    assert!(
        !current.lines().any(|l| l.ends_with(' ')),
        "the generated document has trailing whitespace, which would make its diffs unreadable"
    );
    let path = golden_path(PROTOCOL_MAJOR, PROTOCOL_MINOR);

    let Ok(recorded) = std::fs::read_to_string(&path) else {
        panic!(
            "protocol {PROTOCOL_MAJOR}.{PROTOCOL_MINOR} has no recorded wire shape.\n\n\
             If the version was just bumped, this is the remaining step: write the document \
             below to {}, and add ({PROTOCOL_MAJOR}, {PROTOCOL_MINOR}) to RECORDED_VERSIONS \
             in tests/wire_shape.rs.\n\n\
             ----- begin {PROTOCOL_MAJOR}.{PROTOCOL_MINOR}.golden -----\n{current}\
             ----- end -----\n",
            path.display()
        )
    };

    // `assert!` and not `assert_eq!`: the operands here are two ~110-line
    // documents, and `assert_eq!` would print both in full as `left:` and
    // `right:` *underneath* the message — three copies of the document,
    // with the one-line diff that says what actually moved scrolled off
    // the top. Measured while proving this guard; the failure message is
    // the only part of it anyone reads.
    assert!(
        recorded == current,
        "\n\nthe daemon's wire shape is not the shape recorded for protocol \
         {PROTOCOL_MAJOR}.{PROTOCOL_MINOR}.\n\n{}\n\n\
         Something on the wire moved. Decide which kind of move it was, and record the \
         decision — both paths change PROTOCOL_MINOR or PROTOCOL_MAJOR in \
         protocol/handshake.rs:\n\n  \
         * additive (a new optional field, a new method, a server frame variant an older \
         peer may skip) -> bump PROTOCOL_MINOR;\n  \
         * breaking (a removed or renamed field, a changed type, a changed `type` tag, a \
         new *client* frame the daemon must understand) -> bump PROTOCOL_MAJOR.\n\n\
         Then add the new pair to RECORDED_VERSIONS and write the current document to \
         tests/wire-shape/<major>.<minor>.golden. The full current document is below.\n\n\
         Editing {} in place is the one fix that is not available: it claims this shape was \
         always protocol {PROTOCOL_MAJOR}.{PROTOCOL_MINOR}, and every peer built against the \
         real one disagrees. That rewrite is what this guard exists to make visible \
         (GH #18).\n\n\
         ----- begin current document -----\n{current}----- end -----\n",
        diff(&recorded, &current),
        path.display(),
    );
}

#[test]
fn the_recorded_versions_are_append_only_and_end_at_this_build() {
    assert!(
        !RECORDED_VERSIONS.is_empty(),
        "no protocol version has a recorded shape at all"
    );

    for pair in RECORDED_VERSIONS.windows(2) {
        assert!(
            pair[0] < pair[1],
            "RECORDED_VERSIONS is not in increasing order: {:?} precedes {:?}. The table is \
             a history, and a row out of order means one was rewritten rather than appended.",
            pair[0],
            pair[1]
        );
    }

    let last = *RECORDED_VERSIONS.last().expect("non-empty");
    assert_eq!(
        last,
        (PROTOCOL_MAJOR, PROTOCOL_MINOR),
        "this build speaks protocol {PROTOCOL_MAJOR}.{PROTOCOL_MINOR} but the newest recorded \
         version is {last:?}. Either the constants moved without a row being added, or a row \
         was added for a version nothing speaks yet."
    );

    // Every row has its record, and every record has its row. Without the
    // second half, renaming a golden to the new version — rather than
    // adding one — would delete an older protocol's shape and stay green.
    let on_disk: BTreeSet<String> = std::fs::read_dir(golden_dir())
        .expect("tests/wire-shape must exist")
        .map(|e| {
            e.expect("dir entry")
                .file_name()
                .to_string_lossy()
                .to_string()
        })
        .filter(|n| n.ends_with(".golden"))
        .collect();
    let expected: BTreeSet<String> = RECORDED_VERSIONS
        .iter()
        .map(|(a, b)| format!("{a}.{b}.golden"))
        .collect();
    assert_eq!(
        on_disk, expected,
        "the recorded shapes on disk are not the versions RECORDED_VERSIONS claims"
    );
}

#[test]
fn the_sample_set_covers_every_variant_serde_knows_about() {
    // The cross-check that makes the hand-written sample lists safe. A new
    // frame variant lands in serde's list the moment it compiles, so the
    // omission of a sample is itself the failure — this is what
    // `KNOWN_SERVER_TYPES`, being hand-kept, cannot do.
    let sampled: Vec<String> = client_frames()
        .iter()
        .map(|f| tag_of(&wire_form(f)))
        .collect();
    assert_eq!(
        sampled,
        serde_variants::<ClientFrame>(tagged_probe()),
        "the ClientFrame samples are not serde's variant list, in order. A variant with no \
         sample is a wire surface this guard cannot see."
    );

    let sampled: Vec<String> = server_frames()
        .iter()
        .map(|f| tag_of(&wire_form(f)))
        .collect();
    assert_eq!(
        sampled,
        serde_variants::<ServerFrame>(tagged_probe()),
        "the ServerFrame samples are not serde's variant list, in order. `Unknown` is \
         deliberately in neither: it is #[serde(skip)] and is not on the wire."
    );
}

// ---------------------------------------------------------------------
// The detectors, tested against answers that are known
//
// Every reader above is a way for this guard to go blind rather than
// red: a `shape` that rendered everything the same, a `debug_field_names`
// that found nothing, a `serde_variants` that returned an empty list and
// a `str_const_declaration` that matched no line would each produce a
// stable document that matched its golden forever. `source_guards.rs`
// asserts its own detector for the same reason.
// ---------------------------------------------------------------------

#[test]
fn the_shape_renderer_separates_the_kinds_the_wire_separates() {
    assert_eq!(shape(&CborValue::Bytes(vec![1, 2])), "bytes");
    assert_eq!(
        shape(&CborValue::Array(vec![CborValue::Integer(1.into())])),
        "[int]",
        "a byte string and an array of integers must not render alike — that difference is \
         what §7.4 chose CBOR for"
    );
    assert_eq!(shape(&CborValue::Text("observer".into())), "\"observer\"");
    assert_eq!(shape(&CborValue::Integer(7.into())), "int");
    assert_eq!(shape(&CborValue::Bool(true)), "bool");
    assert_eq!(shape(&CborValue::Null), "null");

    // Values do not move the document; keys and kinds do.
    let with = |k: &str, v: CborValue| CborValue::Map(vec![(CborValue::Text(k.into()), v)]);
    assert_eq!(
        shape(&with("a", CborValue::Integer(1.into()))),
        shape(&with("a", CborValue::Integer(999.into()))),
        "a changed sample value must not read as a wire change"
    );
    assert_ne!(
        shape(&with("a", CborValue::Integer(1.into()))),
        shape(&with("b", CborValue::Integer(1.into()))),
        "a renamed key must read as a wire change"
    );
    assert_ne!(
        shape(&with("a", CborValue::Integer(1.into()))),
        shape(&with("a", CborValue::Text("1".into()))),
        "a retyped field must read as a wire change"
    );
}

#[test]
fn the_declared_field_scanner_reads_names_and_not_values() {
    assert_eq!(
        debug_field_names(r#"Attach { session: "s", mode: ReadWrite }"#),
        ["session", "mode"]
    );
    // A `None` is a field the encoder omits and this scanner must not.
    assert_eq!(
        debug_field_names("ProtocolError { reason: \"r\", frame_kind: None }"),
        ["reason", "frame_kind"]
    );
    // Nesting must not contribute its own fields, or every inner struct
    // would inflate the record.
    assert_eq!(
        debug_field_names(r#"X { a: Some("q"), b: Y { c: 1 }, d: [1, 2] }"#),
        ["a", "b", "d"]
    );
    // A colon inside sample text is not a field boundary.
    assert_eq!(
        debug_field_names(r#"X { a: "postgres://u:p@h" }"#),
        ["a"],
        "text is skipped wholesale, or a redaction fixture would invent fields"
    );
    // A unit variant has no fields, and that is not the same as a
    // scanner that found none.
    assert!(debug_field_names("Detach").is_empty());
    assert_eq!(
        declared_fields(&ClientFrame::Resize { cols: 1, rows: 1 }),
        ["cols", "rows"],
        "the scanner does not read the live type it is pointed at"
    );
    // `declared_fields` sorts and `debug_field_names` does not: a pure
    // field reorder must not read as a wire change, but the parser still
    // has to be shown reading in the order it was given.
    assert_eq!(debug_field_names("X { b: 1, a: 2 }"), ["b", "a"]);
    assert_eq!(
        declared_fields(&ServerFrame::Detached { reason: STR.into() }),
        ["reason"]
    );
}

#[test]
fn serde_reports_its_variant_list_in_the_form_this_guard_reads() {
    // All three phrasings, because the count decides which one serde
    // uses and this guard met the two-variant form only after being
    // written against the three-variant one.
    assert_eq!(
        variants_in("unknown variant `z`, expected `only`"),
        ["only"]
    );
    assert_eq!(
        variants_in("unknown variant `z`, expected `a` or `b`"),
        ["a", "b"]
    );
    assert_eq!(
        variants_in("unknown variant `z`, expected one of `a`, `b`, `c`"),
        ["a", "b", "c"]
    );
    // The rejected discriminator itself is before `expected` and must
    // not be read back as a variant.
    assert!(!variants_in("unknown variant `z`, expected `a` or `b`").contains(&"z".to_string()));

    // Literals, not `ClientKind::Shim.as_str()`: this asserts that the
    // extraction returns the *wire* spellings, and a comparison against
    // the same constants the renderer used could not tell an empty
    // result from a right one.
    assert_eq!(
        serde_variants::<ClientKind>(plain_probe()),
        ["shim", "cli", "ui-bridge"],
        "the extraction lost serde's #[serde(rename)] spellings"
    );
    assert_eq!(
        serde_variants::<AttachRole>(plain_probe()),
        ["interactive", "observer"],
        "rename_all = lowercase must survive the extraction"
    );
    assert_eq!(
        serde_variants::<AttachMode>(plain_probe()),
        ["ReadWrite", "ReadOnly"],
        "§7.5's one CamelCase vocabulary, inherited from §4.3"
    );
    // And the internally-tagged form, which is the shape both frame
    // catalogues use.
    let server = serde_variants::<ServerFrame>(tagged_probe());
    assert!(
        server.contains(&"Attached".to_string()) && server.len() >= 9,
        "the tagged-enum extraction is not reading the catalogue: {server:?}"
    );
    assert!(
        !server.contains(&"Unknown".to_string()),
        "ServerFrame::Unknown is #[serde(skip)] and must not be recorded as wire surface"
    );
}

#[test]
fn the_diff_reports_an_insertion_as_one_line_and_not_as_a_shift() {
    // The measured regression: a positional diff called every line after
    // an insertion a change. The failure message is the only part of a
    // guard anyone reads, so this is asserted rather than eyeballed.
    let before = "a\nb\nc";
    let after = "a\nNEW\nb\nc";
    assert_eq!(diff(before, after), "  +NEW");
    assert_eq!(diff(after, before), "  -NEW");
    assert_eq!(diff(before, before), "");
    assert_eq!(diff("a\nb", "a\nB"), "  -b\n  +B");
}

#[test]
fn the_token_scanner_matches_declarations_and_not_prose() {
    assert_eq!(
        str_const_declaration(r#"pub const METHOD_HANDSHAKE: &str = "holdfast/handshake";"#),
        Some(r#"METHOD_HANDSHAKE = "holdfast/handshake""#.to_string())
    );
    assert_eq!(
        str_const_declaration(r#"/// `pub const METHOD_X: &str = "x";` in prose"#),
        None,
        "a comment that quotes a declaration must not enter the document, which is how a \
         scanner gets deleted"
    );
    assert_eq!(
        str_const_declaration("pub const MAX_FRAME_BYTES: usize = 16 * 1024 * 1024;"),
        None,
        "only &str consts are wire vocabulary"
    );

    // And against the real tree: the scan must reach both files that
    // carry tokens, or it would report a shrinking vocabulary as stable.
    let tokens = wire_tokens();
    assert!(
        tokens.contains(&r#"METHOD_HANDSHAKE = "holdfast/handshake""#.to_string()),
        "the scan does not reach protocol/method.rs: {tokens:?}"
    );
    assert!(
        tokens.contains(&r#"REJECT_CLIENT_TOO_NEW = "client_protocol_too_new""#.to_string()),
        "the scan does not reach protocol/handshake.rs: {tokens:?}"
    );
}
