//! One request's cancellation, deadline and size budget — carried
//! across component boundaries instead of re-derived at each of them
//! (GH #126, GH #127).
//!
//! ## Why this exists
//!
//! Before it, every boundary enforced what it happened to know locally.
//! `request_secret_input` knew `timeout_secs` and `max_secret_bytes`;
//! `secret::provider` knew `keychain_provider_timeout_secs`;
//! `inject_resolved` knew neither and wrote whatever it was handed; and
//! the MCP shim knew a request had been cancelled and had nowhere to say
//! so. The three failures in GH #126 and the one in GH #127 are four
//! readings of that single absence, which is why they are fixed by one
//! type rather than by four patches.
//!
//! ## The shape
//!
//! [`RequestContext`] is **three facts and no behaviour**: when this
//! request must be over, how many bytes of credential it may carry, and
//! whether whoever asked for it has gone away. It is `Clone` and cheap,
//! because it has to cross a `tokio::task::spawn_blocking` hop — task
//! locals do not, which is the rule `crate::mcp::caller` already states
//! for the caller identity.
//!
//! ## How it travels
//!
//! Two mechanisms, and the split is not arbitrary.
//!
//! * **A task-local, at the daemon's dispatch boundary.** The tool
//!   handlers' signatures are generated by `#[tool]` and cannot take an
//!   extra parameter, and `mcp::passthrough::call_tool` builds no
//!   context of its own. So `daemon::server::dispatch_tool` scopes the
//!   call, exactly as it already scopes [`crate::mcp::caller`], and
//!   [`current`] reads it back inside the handler. This carries the
//!   **cancellation** half only: the daemon boundary has no opinion on
//!   any tool's deadline or byte budget.
//! * **An explicit parameter, from the handler down.** The handler
//!   narrows what it read with its own `timeout_secs` and
//!   `max_secret_bytes` and passes the result by reference through
//!   collection, approval and injection. Explicit, because the chain
//!   crosses `spawn_blocking` twice and a task-local would silently
//!   become [`RequestContext::detached`] on the far side — which is the
//!   failure mode that reads as fixed and is not.
//!
//! ## What it deliberately is not
//!
//! Not a cancellation mechanism for *every* tool. A cancel that aborted
//! an arbitrary tool future mid-`await` would drop
//! `request_secret_input`'s receiver while its slot still held the
//! sender, which is GH #127's own bug arrived at from the other side.
//! Cancellation here is **cooperative**: the token reaches every tool,
//! and `request_secret_input` is the only one that reads it. A tool that
//! ignores it runs to completion exactly as it does today. See
//! `daemon::server::dispatch_tool`.

use std::future::Future;
use std::sync::Arc;
use std::time::{Duration, Instant};

use tokio::sync::watch;

/// A one-way flag that an async waiter and a blocking thread can both
/// read.
///
/// **Both readers are required, which is what rules out a bare
/// `oneshot`.** `await_secret` waits on it inside a `select!`; the
/// provider's `try_wait` poll loop — an ordinary OS thread on the
/// blocking pool — asks it between polls. So the primitive has to offer
/// an `await` *and* a load, and it has to be `Clone` because the
/// blocking side gets its own copy.
///
/// ## Why `watch` and not a flag beside a `Notify`
///
/// The obvious hand-rolled version is an `AtomicBool` and a `Notify`,
/// and this was written that way first. `notify_waiters` wakes only
/// waiters already registered and stores no permit, so such a
/// `cancelled()` must **register before it loads the flag** — and a
/// version that loads first is a lost wakeup: the flag set, the waiter
/// parked forever. That is the worst available failure on a path whose
/// entire job is to stop a wait.
///
/// **That ordering had no test that could catch it, and the mutation
/// ladder is how that was found rather than argued.** Swapping the two
/// statements left every behavioural row green, because any test that
/// gets the waiter parked has already left the window — it is between
/// two statements on one task. So the invariant is not defended here, it
/// is removed: `watch::Receiver::wait_for` evaluates its predicate
/// against the **current** value before it waits, so there is no
/// check-then-register to get wrong and the guarantee belongs to tokio
/// rather than to an ordering this file asserts about itself.
#[derive(Clone, Debug)]
pub struct CancelSignal(Arc<watch::Sender<bool>>);

impl Default for CancelSignal {
    fn default() -> Self {
        Self::new()
    }
}

impl CancelSignal {
    /// A signal nobody has cancelled yet.
    pub fn new() -> Self {
        Self(Arc::new(watch::channel(false).0))
    }

    /// Cancel, and wake every waiter. `true` on the first call only.
    ///
    /// Idempotent on purpose: a cancel can arrive twice — once from the
    /// MCP client's `notifications/cancelled` and once from a retry —
    /// and the second must not be an error.
    ///
    /// `send_if_modified` rather than a load and then a `send`, so *"was
    /// I first"* is decided under the same lock that sets the value.
    pub fn cancel(&self) -> bool {
        let mut first = false;
        self.0.send_if_modified(|v| {
            if *v {
                false
            } else {
                *v = true;
                first = true;
                true
            }
        });
        first
    }

    /// Has this request been cancelled? Cheap enough for the provider's
    /// 2 ms poll.
    pub fn is_cancelled(&self) -> bool {
        *self.0.borrow()
    }

    /// Resolve once cancelled; park otherwise.
    ///
    /// **It cannot resolve early.** `wait_for` fails when every sender is
    /// gone, and this type *is* the sender — held in the `Arc` the
    /// waiter's own `&self` borrows — so the channel cannot close while
    /// anybody is waiting on it. A version that let the sender go would
    /// resolve at once and report a cancellation nobody asked for.
    pub async fn cancelled(&self) {
        let mut rx = self.0.subscribe();
        let _ = rx.wait_for(|v| *v).await;
    }
}

/// Why a request is over before it was answered.
///
/// **Two endings and not one**, because GH #105 is the bug that comes
/// from reporting one ending as another: a caller that cancelled and a
/// deadline that elapsed are told apart here so that every boundary
/// below can keep telling them apart. See
/// `secret::CancelReason::CallerCancelled`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RequestEnded {
    /// Whoever asked for this went away — an MCP `notifications/cancelled`
    /// that reached the daemon.
    Cancelled,
    /// The deadline this request was given elapsed.
    Expired,
}

/// The three facts one request carries everywhere it goes.
///
/// **Constructed narrow and never widened.** [`detached`](Self::detached)
/// is the only constructor that produces an unbounded context, and it
/// exists for the paths that genuinely have no caller — §9.6's
/// unattended autofill, and every in-process test. Everything else
/// starts from [`current`] and narrows.
#[derive(Clone, Debug)]
pub struct RequestContext {
    cancel: CancelSignal,
    deadline: Option<Instant>,
    max_bytes: Option<u32>,
}

impl RequestContext {
    /// No caller, no deadline, no byte budget.
    ///
    /// **Not a default to reach for.** [`current`] answers this outside
    /// a dispatch scope, which is correct for an in-process server and
    /// wrong for a daemon that forgot to open one — the same asymmetry
    /// `crate::mcp::caller::Caller::InProcess` is spelled apart for.
    pub fn detached() -> Self {
        Self {
            cancel: CancelSignal::new(),
            deadline: None,
            max_bytes: None,
        }
    }

    /// A context whose cancellation is `cancel`'s.
    pub fn with_cancel(cancel: CancelSignal) -> Self {
        Self {
            cancel,
            deadline: None,
            max_bytes: None,
        }
    }

    /// This request must be over by `deadline`.
    ///
    /// **The narrower of the two wins**, so a stage that hands down its
    /// own budget can never lengthen the one it was given. That is the
    /// property `request_secret_input`'s single `call_start` stamp exists
    /// for, made structural: there is no way to spell "a fresh full
    /// window" through this type.
    #[must_use]
    pub fn with_deadline(mut self, deadline: Instant) -> Self {
        self.deadline = Some(match self.deadline {
            Some(existing) => existing.min(deadline),
            None => deadline,
        });
        self
    }

    /// This request may carry at most `max_bytes` bytes of credential.
    ///
    /// The narrower of the two wins, for the same reason as
    /// [`with_deadline`](Self::with_deadline).
    #[must_use]
    pub fn with_max_bytes(mut self, max_bytes: u32) -> Self {
        self.max_bytes = Some(match self.max_bytes {
            Some(existing) => existing.min(max_bytes),
            None => max_bytes,
        });
        self
    }

    pub fn cancel_signal(&self) -> &CancelSignal {
        &self.cancel
    }

    pub fn is_cancelled(&self) -> bool {
        self.cancel.is_cancelled()
    }

    /// Resolve once this request is cancelled; park forever otherwise.
    pub async fn cancelled(&self) {
        self.cancel.cancelled().await;
    }

    pub fn deadline(&self) -> Option<Instant> {
        self.deadline
    }

    pub fn max_bytes(&self) -> Option<u32> {
        self.max_bytes
    }

    /// How long is left, as of `now`. `Some(ZERO)` for a deadline that
    /// has already passed, `None` for no deadline at all — and the two
    /// are different answers, which is why this is not a `Duration`.
    pub fn remaining(&self, now: Instant) -> Option<Duration> {
        self.deadline.map(|d| d.saturating_duration_since(now))
    }

    /// `budget`, narrowed to whatever is left of this request.
    ///
    /// The one arithmetic every bounded stage shares: a provider budget,
    /// an approval window and a pipe-collection wait are all "the smaller
    /// of what this stage allows and what the request has left".
    pub fn bounded(&self, now: Instant, budget: Duration) -> Duration {
        match self.remaining(now) {
            Some(left) => budget.min(left),
            None => budget,
        }
    }

    /// Is this request over — and if so, how?
    ///
    /// **Cancellation is checked first**, deliberately. A request that is
    /// both cancelled and expired is reported cancelled, because the
    /// cancel is the fact about *who asked* and the expiry is a fact
    /// about the clock; a human at an attached client needs the first.
    pub fn ended(&self, now: Instant) -> Option<RequestEnded> {
        if self.is_cancelled() {
            return Some(RequestEnded::Cancelled);
        }
        match self.deadline {
            Some(d) if now >= d => Some(RequestEnded::Expired),
            _ => None,
        }
    }

    /// Does `len` fit this request's byte budget?
    ///
    /// `true` when there is no budget, which is [`detached`](Self::detached)
    /// and nothing else on any path a credential takes.
    pub fn fits(&self, len: usize) -> bool {
        self.max_bytes.is_none_or(|cap| len <= cap as usize)
    }
}

tokio::task_local! {
    static CONTEXT: RequestContext;
}

/// Run `fut` with `ctx` as the current request's context.
pub async fn with_context<F>(ctx: RequestContext, fut: F) -> F::Output
where
    F: Future,
{
    CONTEXT.scope(ctx, fut).await
}

/// The current request's context, or [`RequestContext::detached`] outside
/// any scope.
///
/// **Read it on the task that is inside the scope.**
/// `tokio::task::spawn_blocking` and `tokio::spawn` do not inherit task
/// locals, so a path that hands work to the blocking pool must capture
/// this *before* it does so and carry the value in — the rule
/// `crate::mcp::caller` already states, and the reason the secret path
/// passes a `&RequestContext` rather than calling this again downstream.
pub fn current() -> RequestContext {
    CONTEXT
        .try_with(Clone::clone)
        .unwrap_or_else(|_| RequestContext::detached())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn a_signal_cancelled_before_the_wait_does_not_park() {
        let s = CancelSignal::new();
        assert!(s.cancel(), "the first cancel reports itself as first");
        assert!(!s.cancel(), "the second does not");
        tokio::time::timeout(Duration::from_secs(5), s.cancelled())
            .await
            .expect("a signal already cancelled must resolve at once");
    }

    /// The lost-wakeup shape, driven rather than reasoned about: the
    /// waiter is parked first and the cancel arrives after.
    #[tokio::test]
    async fn a_signal_cancelled_during_the_wait_wakes_it() {
        let s = CancelSignal::new();
        let waiter = {
            let s = s.clone();
            tokio::spawn(async move { s.cancelled().await })
        };
        // Yield enough for the waiter to reach `enable()` and park.
        for _ in 0..8 {
            tokio::task::yield_now().await;
        }
        assert!(!s.is_cancelled());
        s.cancel();
        tokio::time::timeout(Duration::from_secs(5), waiter)
            .await
            .expect("the parked waiter was never woken")
            .expect("the waiter task");
    }

    #[tokio::test]
    async fn a_context_that_is_never_cancelled_parks() {
        let ctx = RequestContext::detached();
        assert!(
            tokio::time::timeout(Duration::from_millis(50), ctx.cancelled())
                .await
                .is_err(),
            "a detached context resolved its cancellation"
        );
    }

    /// Neither knob can be widened once set — the property that makes
    /// `1.5×` the declared window unspellable.
    #[test]
    fn narrowing_is_the_only_direction() {
        let now = Instant::now();
        let ctx = RequestContext::detached()
            .with_deadline(now + Duration::from_secs(10))
            .with_deadline(now + Duration::from_secs(2))
            .with_deadline(now + Duration::from_secs(30));
        let left = ctx.remaining(now).expect("a deadline");
        assert!(
            left <= Duration::from_secs(2),
            "a later deadline widened the window: {left:?}"
        );

        let ctx = RequestContext::detached()
            .with_max_bytes(4096)
            .with_max_bytes(16)
            .with_max_bytes(65536);
        assert_eq!(ctx.max_bytes(), Some(16));
    }

    #[test]
    fn bounded_is_the_smaller_of_the_two() {
        let now = Instant::now();
        let unbounded = RequestContext::detached();
        assert_eq!(
            unbounded.bounded(now, Duration::from_secs(10)),
            Duration::from_secs(10),
            "no deadline must not shorten a stage's own budget"
        );
        let ctx = unbounded.with_deadline(now + Duration::from_secs(3));
        assert_eq!(
            ctx.bounded(now, Duration::from_secs(10)),
            Duration::from_secs(3)
        );
        assert_eq!(
            ctx.bounded(now, Duration::from_secs(1)),
            Duration::from_secs(1)
        );
    }

    /// A cancel and an expiry are different endings, and the cancel wins.
    #[test]
    fn a_cancelled_and_expired_request_reports_the_cancel() {
        let now = Instant::now();
        let ctx = RequestContext::detached().with_deadline(now - Duration::from_secs(1));
        assert_eq!(ctx.ended(now), Some(RequestEnded::Expired));
        ctx.cancel_signal().cancel();
        assert_eq!(ctx.ended(now), Some(RequestEnded::Cancelled));
    }

    #[test]
    fn fits_is_inclusive_and_absent_means_unbounded() {
        let ctx = RequestContext::detached();
        assert!(ctx.fits(usize::MAX), "no budget refused a value");
        let ctx = ctx.with_max_bytes(7);
        assert!(ctx.fits(7), "a value exactly at the budget was refused");
        assert!(!ctx.fits(8));
    }

    #[tokio::test]
    async fn the_task_local_is_detached_outside_a_scope_and_carried_inside_one() {
        assert!(
            current().deadline().is_none() && !current().is_cancelled(),
            "a context leaked in from outside any scope"
        );
        let signal = CancelSignal::new();
        let carried = with_context(RequestContext::with_cancel(signal.clone()), async {
            signal.cancel();
            current().is_cancelled()
        })
        .await;
        assert!(carried, "the scoped context did not reach `current`");
        assert!(!current().is_cancelled(), "the scope outlived itself");
    }
}
